CREATE TABLE stores (
    id INTEGER PRIMARY KEY,
    user_id INTEGER NOT NULL,
    template_id INTEGER NOT NULL,
    store_name VARCHAR(255) UNIQUE NOT NULL,
    industry VARCHAR(100) NOT NULL CHECK (industry IN (
        'ecommerce',
        'technology',
        'fashion',
        'health and wellness',
        'education',
        'food and beverage',
        'travel and tourism',
        'real estate',
        'entertainment',
        'automotive',
        'finance',
        'legal services',
        'manufacturing',
        'agriculture',
        'nonprofit and charity',
        'sports and recreation',
        'media and publishing',
        'home services',
        'beauty and personal care',
        'marketing and advertising',
        'retail',
        'logistics and supply chain',
        'energy and utilities',
        'other'
    )),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (template_id) REFERENCES templates(id) ON DELETE CASCADE ON UPDATE CASCADE
);
