version: '3.9'
services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: fortune_serving
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: fortune_serving_db
    volumes:
      - ./src/db/postgres/migrations:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
