openapi: 3.0.0
info:
  title: fortune serving api
  description: API portfolio, documented by [Daryl Deogracias](https://daryldeogracias.com/).
  version: 1.0.0

# servers:
#   - url: http://api.example.com/v1
#     description: Optional server description, e.g. Main (production) server
#   - url: http://staging-api.example.com
#     description: Optional server description, e.g. Internal staging server for testing

paths:

components:
  schemas:
    users:
      $ref: "./users.yaml"
    templates: 
      $ref: "./templates.yaml"
    stores:
      $ref: "./stores.yaml"
    categories:
      $ref: "./categories.yaml"
    addresses: 
      $ref: "./addresses.yaml"
    items:
      $ref: "./items.yaml"