openapi: 3.0.0
info:
  title: "fortune serving api"
  description: "API portfolio, documented by [Daryl Deogracias](https://daryldeogracias.com/)."
  version: 1.0.0

# servers:
#   - url: http://api.example.com/v1
#     description: Optional server description, e.g. Main (production) server
#   - url: http://staging-api.example.com
#     description: Optional server description, e.g. Internal staging server for testing

paths:
  /users:
    post:
      tags:
        - "Users"
      summary: "Create a new user."
    get:
      tags:
        - "Users"
      summary: "Retrieve a paginated list of users."

  /users/{id}:
    get:
      tags:
        - "Users"
      summary: "Retrieve a user by ID."
    patch:
      tags:
        - "Users"
      summary: "Update user fields by ID."
    delete:
      tags:
        - "Users"
      summary: "Delete a user by ID."

  /users/{id}/addresses:
    get:
      tags:
        - "Users"
      summary: "Retrieve a user's addresses."
    post:
      tags:
        - "Users"
      summary: "Add a new address for a user."

components:
  schemas:
    user:
      $ref: "./user.yaml"
    template:
      $ref: "./template.yaml"
    store:
      $ref: "./store.yaml"
    category:
      $ref: "./category.yaml"
    address:
      $ref: "./address.yaml"
    item:
      $ref: "./item.yaml"
